// Code generated by the Encore v1.51.10 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-bilingual-church-community-app-8dn2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the bilingual-church-community-app-8dn2 Encore application.
 */
export default class Client {
    public readonly announcements: announcements.ServiceClient
    public readonly bulletin: bulletin.ServiceClient
    public readonly church: church.ServiceClient
    public readonly donations: donations.ServiceClient
    public readonly events: events.ServiceClient
    public readonly media: media.ServiceClient
    public readonly prayers: prayers.ServiceClient
    public readonly sermons: sermons.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.announcements = new announcements.ServiceClient(base)
        this.bulletin = new bulletin.ServiceClient(base)
        this.church = new church.ServiceClient(base)
        this.donations = new donations.ServiceClient(base)
        this.events = new events.ServiceClient(base)
        this.media = new media.ServiceClient(base)
        this.prayers = new prayers.ServiceClient(base)
        this.sermons = new sermons.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace announcements {
    export interface Announcement {
        id: number
        titleEn: string
        titleEs: string
        contentEn: string
        contentEs: string
        priority: string
        createdAt: string
        createdBy: string
    }

    export interface Announcement {
        id: number
        titleEn: string
        titleEs: string
        contentEn: string
        contentEs: string
        priority: string
        createdAt: string
        createdBy: string
    }

    export interface CreateAnnouncementRequest {
        titleEn: string
        titleEs: string
        contentEn: string
        contentEs: string
        priority: "low" | "normal" | "high" | "urgent"
        passcode: string
    }

    export interface DeleteAnnouncementRequest {
        passcode: string
    }

    export interface DeleteAnnouncementResponse {
        success: true
    }

    export interface ListAnnouncementsRequest {
        limit: number
    }

    export interface ListAnnouncementsResponse {
        announcements: Announcement[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
        }

        /**
         * Creates a new church announcement.
         */
        public async create(params: CreateAnnouncementRequest): Promise<Announcement> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/announcements`, JSON.stringify(params))
            return await resp.json() as Announcement
        }

        /**
         * Lists church announcements, ordered by priority and date.
         */
        public async list(params: ListAnnouncementsRequest): Promise<ListAnnouncementsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/announcements`, undefined, {query})
            return await resp.json() as ListAnnouncementsResponse
        }

        public async remove(id: number, params: DeleteAnnouncementRequest): Promise<DeleteAnnouncementResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/announcements/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeleteAnnouncementResponse
        }
    }
}

export namespace auth {
    export interface AuthParams {
        authorization?: string
    }
}

export namespace bulletin {
    export interface BoardResponse {
        prayers: PrayerWithComments[]
        posts: BulletinPost[]
    }

    export interface BulletinComment {
        id: number
        authorName: string
        content: string
        createdAt: string
    }

    export interface BulletinComment {
        id: number
        postId: number | null
        prayerId: number | null
        authorName: string
        content: string
        createdAt: string
    }

    export interface BulletinPost {
        id: number
        title: string
        content: string
        authorName: string
        createdAt: string
        comments: BulletinComment[]
    }

    export interface BulletinPost {
        id: number
        title: string
        content: string
        authorName: string
        createdAt: string
    }

    export interface CreateCommentRequest {
        targetType: "post" | "prayer"
        targetId: number
        authorName: string
        content: string
    }

    export interface CreatePostRequest {
        title: string
        content: string
        authorName: string
    }

    export interface DeletePostRequest {
        passcode: string
    }

    export interface DeletePostResponse {
        success: true
    }

    export interface PrayerWithComments {
        id: number
        title: string
        description: string
        isAnonymous: boolean
        userId: string
        userName: string | null
        prayerCount: number
        createdAt: string
        comments: BulletinComment[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.board = this.board.bind(this)
            this.createComment = this.createComment.bind(this)
            this.createPost = this.createPost.bind(this)
            this.removePost = this.removePost.bind(this)
        }

        public async board(): Promise<BoardResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/bulletin/board`)
            return await resp.json() as BoardResponse
        }

        public async createComment(params: CreateCommentRequest): Promise<BulletinComment> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/bulletin/comments`, JSON.stringify(params))
            return await resp.json() as BulletinComment
        }

        public async createPost(params: CreatePostRequest): Promise<BulletinPost> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/bulletin/posts`, JSON.stringify(params))
            return await resp.json() as BulletinPost
        }

        public async removePost(id: number, params: DeletePostRequest): Promise<DeletePostResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/bulletin/posts/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeletePostResponse
        }
    }
}

export namespace church {
    export interface ChurchInfo {
        nameEn: string
        nameEs: string
        address: string
        phone: string
        email: string
        serviceTimesEn: string
        serviceTimesEs: string
        descriptionEn: string | null
        descriptionEs: string | null
        facebookPageUrl: string | null
        latitude: number | null
        longitude: number | null
    }

    export interface ChurchInfo {
        nameEn: string
        nameEs: string
        address: string
        phone: string
        email: string
        serviceTimesEn: string
        serviceTimesEs: string
        descriptionEn: string | null
        descriptionEs: string | null
        facebookPageUrl: string | null
        latitude: number | null
        longitude: number | null
    }

    export interface SendNotificationRequest {
        title: string
        body: string
        icon?: string
        badge?: string
        tag?: string
        data?: any
        actions?: {
            action: string
            title: string
            icon?: string
        }[]
    }

    export interface TriviaLevel {
        id: string
        name: string
        description: string | null
        "shuffle_questions": boolean
        "time_limit": number
        "passing_score": number
        "created_at": string
    }

    export interface TriviaQuestion {
        id: number
        "question_en": string
        "question_es": string
        "options_en": string
        "options_es": string
        "correct_answer": number
        category: string
        "level_id": string
        "created_at": string
    }

    export interface TriviaResponse {
        levels: TriviaLevel[]
        questions: TriviaQuestion[]
    }

    export interface UpdateChurchInfoRequest {
        nameEn?: string
        nameEs?: string
        address?: string
        phone?: string
        email?: string
        serviceTimesEn?: string
        serviceTimesEs?: string
        descriptionEn?: string
        descriptionEs?: string
        facebookPageUrl?: string
        latitude?: number
        longitude?: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createLevel = this.createLevel.bind(this)
            this.createQuestion = this.createQuestion.bind(this)
            this.deleteLevel = this.deleteLevel.bind(this)
            this.deleteQuestion = this.deleteQuestion.bind(this)
            this.getStats = this.getStats.bind(this)
            this.getTrivia = this.getTrivia.bind(this)
            this.info = this.info.bind(this)
            this.sendAnnouncementNotification = this.sendAnnouncementNotification.bind(this)
            this.sendLivestreamNotification = this.sendLivestreamNotification.bind(this)
            this.sendNewsNotification = this.sendNewsNotification.bind(this)
            this.sendToAll = this.sendToAll.bind(this)
            this.setupTriviaTables = this.setupTriviaTables.bind(this)
            this.subscribe = this.subscribe.bind(this)
            this.testTriviaDB = this.testTriviaDB.bind(this)
            this.unsubscribe = this.unsubscribe.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Create level
         */
        public async createLevel(params: {
    id: string
    name: string
    description?: string
    "shuffle_questions"?: boolean
    "time_limit"?: number
    "passing_score"?: number
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trivia/simple/level`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Create question
         */
        public async createQuestion(params: {
    "question_en": string
    "question_es": string
    "options_en": string[]
    "options_es": string[]
    "correct_answer": number
    category: string
    "level_id": string
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trivia/simple/question`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Delete level
         */
        public async deleteLevel(id: string, params: {
    passcode?: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/trivia/simple/level/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Delete question
         */
        public async deleteQuestion(id: number, params: {
    passcode?: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/trivia/simple/question/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Get subscription statistics
         */
        public async getStats(): Promise<{
    totalSubscribers: number
    activeSubscriptions: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/notifications/stats`)
            return await resp.json() as {
    totalSubscribers: number
    activeSubscriptions: number
}
        }

        /**
         * Get all trivia data
         */
        public async getTrivia(): Promise<TriviaResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/trivia/simple`)
            return await resp.json() as TriviaResponse
        }

        /**
         * Retrieves church contact information and location.
         */
        public async info(): Promise<ChurchInfo> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/church/info`)
            return await resp.json() as ChurchInfo
        }

        /**
         * Send notification for announcements
         */
        public async sendAnnouncementNotification(params: {
    title: string
    body: string
    announcementId?: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/announcement`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Send notification for livestream reminder
         */
        public async sendLivestreamNotification(params: {
    title?: string
    body?: string
    streamTime?: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/livestream`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Send notification for news
         */
        public async sendNewsNotification(params: {
    title: string
    body: string
    newsId?: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/news`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Send notification to all subscribers
         */
        public async sendToAll(params: SendNotificationRequest): Promise<{
    success: boolean
    message: string
    sent: number
    failed: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/send-all`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
    sent: number
    failed: number
}
        }

        public async setupTriviaTables(): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trivia/setup-tables`)
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Subscribe to push notifications
         */
        public async subscribe(params: {
    endpoint: string
    keys: {
        p256dh: string
        auth: string
    }
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/subscribe`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        public async testTriviaDB(): Promise<{
    success: boolean
    message: string
    tablesExist: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/trivia/test-db`)
            return await resp.json() as {
    success: boolean
    message: string
    tablesExist: boolean
}
        }

        /**
         * Unsubscribe from push notifications
         */
        public async unsubscribe(params: {
    endpoint: string
}): Promise<{
    success: boolean
    message: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/unsubscribe`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    message: string
}
        }

        /**
         * Updates church information.
         */
        public async update(params: UpdateChurchInfoRequest): Promise<ChurchInfo> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/church/info`, JSON.stringify(params))
            return await resp.json() as ChurchInfo
        }
    }
}

export namespace donations {
    export interface ConfirmDonationRequest {
        success: boolean
    }

    export interface ConfirmDonationResponse {
        success: boolean
    }

    export interface CreateDonationRequest {
        amount: number
        donationType: "general" | "missions" | "building" | "other"
        message?: string
    }

    export interface Donation {
        id: number
        userId: string
        userName: string | null
        amount: number
        currency: string
        status: string
        donationType: string
        message: string | null
        createdAt: string
        clientSecret: string
    }

    export interface Donation {
        id: number
        userId: string
        userName: string | null
        amount: number
        currency: string
        status: string
        donationType: string
        message: string | null
        createdAt: string
    }

    export interface ListDonationsRequest {
        limit: number
    }

    export interface ListDonationsResponse {
        donations: Donation[]
        total: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.confirm = this.confirm.bind(this)
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Confirms a donation payment status.
         */
        public async confirm(donationId: number, params: ConfirmDonationRequest): Promise<ConfirmDonationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/donations/${encodeURIComponent(donationId)}/confirm`, JSON.stringify(params))
            return await resp.json() as ConfirmDonationResponse
        }

        /**
         * Creates a new donation and returns a payment intent.
         */
        public async create(params: CreateDonationRequest): Promise<Donation> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/donations`, JSON.stringify(params))
            return await resp.json() as Donation
        }

        /**
         * Lists completed donations.
         */
        public async list(params: ListDonationsRequest): Promise<ListDonationsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/donations`, undefined, {query})
            return await resp.json() as ListDonationsResponse
        }
    }
}

export namespace events {
    export interface CancelRSVPResponse {
        success: boolean
    }

    export interface CreateEventRequest {
        titleEn: string
        titleEs: string
        descriptionEn?: string
        descriptionEs?: string
        eventDate: string
        location: string
        maxAttendees?: number
        passcode: string
    }

    export interface DeleteEventRequest {
        passcode: string
    }

    export interface DeleteEventResponse {
        success: true
    }

    export interface Event {
        id: number
        titleEn: string
        titleEs: string
        descriptionEn: string | null
        descriptionEs: string | null
        eventDate: string
        location: string
        maxAttendees: number | null
        createdAt: string
        createdBy: string
        rsvpCount: number
    }

    export interface Event {
        id: number
        titleEn: string
        titleEs: string
        descriptionEn: string | null
        descriptionEs: string | null
        eventDate: string
        location: string
        maxAttendees: number | null
        createdAt: string
        createdBy: string
        rsvpCount: number
    }

    export interface ListEventsRequest {
        upcoming: boolean
    }

    export interface ListEventsResponse {
        events: Event[]
    }

    export interface RSVPRequest {
        attendees: number
        participantId?: string | null
        name?: string | null
    }

    export interface RSVPResponse {
        success: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelRsvp = this.cancelRsvp.bind(this)
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.rsvp = this.rsvp.bind(this)
        }

        /**
         * Cancels an RSVP for an event.
         */
        public async cancelRsvp(eventId: number): Promise<CancelRSVPResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(eventId)}/rsvp`)
            return await resp.json() as CancelRSVPResponse
        }

        /**
         * Creates a new church event.
         */
        public async create(params: CreateEventRequest): Promise<Event> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events`, JSON.stringify(params))
            return await resp.json() as Event
        }

        /**
         * Lists all church events.
         */
        public async list(params: ListEventsRequest): Promise<ListEventsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                upcoming: String(params.upcoming),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/events`, undefined, {query})
            return await resp.json() as ListEventsResponse
        }

        public async remove(id: number, params: DeleteEventRequest): Promise<DeleteEventResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/events/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeleteEventResponse
        }

        /**
         * Creates or updates an RSVP for an event.
         */
        public async rsvp(eventId: number, params: RSVPRequest): Promise<RSVPResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/events/${encodeURIComponent(eventId)}/rsvp`, JSON.stringify(params))
            return await resp.json() as RSVPResponse
        }
    }
}

export namespace media {
    export interface BrowserUploadRequest {
        fileName: string
        contentType: string
        base64Data: string
        passcode: string
    }

    export interface BrowserUploadResponse {
        publicUrl: string
        name: string
    }

    export interface DeleteRequest {
        name: string
        passcode: string
    }

    export interface DeleteResponse {
        success: boolean
        message: string
    }

    export interface GetPlaylistResponse {
        url: string | null
    }

    export interface ListMediaResponse {
        items: MediaItem[]
    }

    export interface ListTracksResponse {
        tracks: TrackItem[]
    }

    export interface MediaItem {
        name: string
        size: number
        url: string
        etag: string
    }

    export interface TrackItem {
        id: string
        name: string
        title: string
        artist: string
        url: string
    }

    export interface UpdatePlaylistRequest {
        passcode: string
        url: string
    }

    export interface UploadUrlRequest {
        fileName: string
        contentType: string
        passcode: string
    }

    export interface UploadUrlResponse {
        uploadUrl: string
        publicUrl: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.browserUpload = this.browserUpload.bind(this)
            this.deleteMedia = this.deleteMedia.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.listTracks = this.listTracks.bind(this)
            this.save = this.save.bind(this)
            this.uploadUrl = this.uploadUrl.bind(this)
        }

        public async browserUpload(params: BrowserUploadRequest): Promise<BrowserUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/media/upload-browser`, JSON.stringify(params))
            return await resp.json() as BrowserUploadResponse
        }

        public async deleteMedia(params: DeleteRequest): Promise<DeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/media/delete`, JSON.stringify(params))
            return await resp.json() as DeleteResponse
        }

        public async get(): Promise<GetPlaylistResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/playlist`)
            return await resp.json() as GetPlaylistResponse
        }

        /**
         * Lists all media files in the gallery.
         */
        public async list(): Promise<ListMediaResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/media`)
            return await resp.json() as ListMediaResponse
        }

        /**
         * Lists all audio tracks stored in the media bucket.
         */
        public async listTracks(): Promise<ListTracksResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/media/tracks`)
            return await resp.json() as ListTracksResponse
        }

        public async save(params: UpdatePlaylistRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/playlist`, JSON.stringify(params))
        }

        /**
         * Generates a signed URL for uploading media files.
         */
        public async uploadUrl(params: UploadUrlRequest): Promise<UploadUrlResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/media/upload-url`, JSON.stringify(params))
            return await resp.json() as UploadUrlResponse
        }
    }
}

export namespace prayers {
    export interface CreatePrayerRequest {
        title: string
        description: string
        isAnonymous: boolean
        authorName?: string | null
    }

    export interface DeletePrayerRequest {
        passcode: string
    }

    export interface DeletePrayerResponse {
        success: true
    }

    export interface ListPrayersRequest {
        limit: number
    }

    export interface ListPrayersResponse {
        prayers: Prayer[]
    }

    export interface PrayRequest {
        participantId?: string | null
    }

    export interface PrayResponse {
        success: boolean
        prayerCount: number
    }

    export interface Prayer {
        id: number
        title: string
        description: string
        isAnonymous: boolean
        userId: string
        userName: string | null
        prayerCount: number
        createdAt: string
    }

    export interface Prayer {
        id: number
        title: string
        description: string
        isAnonymous: boolean
        userId: string
        userName: string | null
        prayerCount: number
        createdAt: string
        userPrayed: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.pray = this.pray.bind(this)
            this.remove = this.remove.bind(this)
        }

        /**
         * Submits a new prayer request.
         */
        public async create(params: CreatePrayerRequest): Promise<Prayer> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/prayers`, JSON.stringify(params))
            return await resp.json() as Prayer
        }

        /**
         * Lists prayer requests, ordered by most recent.
         */
        public async list(params: ListPrayersRequest): Promise<ListPrayersResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/prayers`, undefined, {query})
            return await resp.json() as ListPrayersResponse
        }

        /**
         * Records that a user has prayed for a request.
         */
        public async pray(prayerId: number, params: PrayRequest): Promise<PrayResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/prayers/${encodeURIComponent(prayerId)}/pray`, JSON.stringify(params))
            return await resp.json() as PrayResponse
        }

        public async remove(id: number, params: DeletePrayerRequest): Promise<DeletePrayerResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passcode: params.passcode,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/prayers/${encodeURIComponent(id)}`, undefined, {query})
            return await resp.json() as DeletePrayerResponse
        }
    }
}

export namespace sermons {
    export interface CreateSermonRequest {
        passcode: string
        title: string
        youtubeUrl: string
    }

    export interface CreateSermonResponse {
        id: number
    }

    export interface DeleteSermonRequest {
        passcode: string
        id: number
    }

    export interface ListSermonsResponse {
        sermons: Sermon[]
    }

    export interface Sermon {
        id: number
        title: string
        youtubeUrl: string
        createdAt: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
        }

        public async create(params: CreateSermonRequest): Promise<CreateSermonResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/sermons`, JSON.stringify(params))
            return await resp.json() as CreateSermonResponse
        }

        public async list(): Promise<ListSermonsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/sermons/recent`)
            return await resp.json() as ListSermonsResponse
        }

        public async remove(params: DeleteSermonRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/sermons/delete`, JSON.stringify(params))
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "bilingual-church-community-app-8dn2-Generated-TS-Client (Encore/v1.51.10)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
